In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mglearn
from sklearn.model_selection import train_test_split

In [9]:
from sklearn.datasets import load_iris
from sklearn.ensemble import GradientBoostingClassifier

iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state=42)

gbrt = GradientBoostingClassifier(learning_rate=0.01, random_state=0)
gbrt.fit(X_train, y_train)

gbrt.decision_function(X_test).shape

(38, 3)

In [10]:
gbrt.decision_function(X_test)

array([[-0.89604809,  1.14724958, -0.82754003],
       [ 1.16113086, -0.80789044, -0.82827067],
       [-0.89091511, -0.77671169,  1.19653416],
       [-0.89604809,  1.14724958, -0.82754003],
       [-0.89763468,  0.96497584, -0.10374792],
       [ 1.16113086, -0.80789044, -0.82827067],
       [-0.89604809,  1.14724958, -0.82754003],
       [-0.89710742, -0.77671169,  1.19653416],
       [-0.89604809,  1.14724958, -0.82754003],
       [-0.89604809,  1.14724958, -0.82754003],
       [-0.89710742, -0.77671169,  1.17829848],
       [ 1.16113086, -0.80789044, -0.82827067],
       [ 1.16113086, -0.80789044, -0.82827067],
       [ 1.16113086, -0.80789044, -0.82827067],
       [ 1.16113086, -0.80789044, -0.82827067],
       [-0.89604809,  1.14724958, -0.82754003],
       [-0.89120824, -0.77671169,  1.19653416],
       [-0.89604809,  1.14724958, -0.82754003],
       [-0.89604809,  1.14724958, -0.82754003],
       [-0.89120824, -0.77671169,  1.19653416],
       [ 1.16113086, -0.80789044, -0.828

In [11]:
# largest score means that a class is more likely
np.argmax(gbrt.decision_function(X_test), axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [12]:
gbrt.predict(X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [19]:
# using predict_proba
gbrt.predict_proba(X_test)

array([[0.10217718, 0.78840034, 0.10942248],
       [0.78347147, 0.10936745, 0.10716108],
       [0.09818072, 0.11005864, 0.79176065],
       [0.10217718, 0.78840034, 0.10942248],
       [0.10360005, 0.66723901, 0.22916094],
       [0.78347147, 0.10936745, 0.10716108],
       [0.10217718, 0.78840034, 0.10942248],
       [0.09763381, 0.11012538, 0.79224081],
       [0.10217718, 0.78840034, 0.10942248],
       [0.10217718, 0.78840034, 0.10942248],
       [0.09905185, 0.11172485, 0.78922331],
       [0.78347147, 0.10936745, 0.10716108],
       [0.78347147, 0.10936745, 0.10716108],
       [0.78347147, 0.10936745, 0.10716108],
       [0.78347147, 0.10936745, 0.10716108],
       [0.10217718, 0.78840034, 0.10942248],
       [0.09815477, 0.1100618 , 0.79178343],
       [0.10217718, 0.78840034, 0.10942248],
       [0.10217718, 0.78840034, 0.10942248],
       [0.09815477, 0.1100618 , 0.79178343],
       [0.78347147, 0.10936745, 0.10716108],
       [0.10178234, 0.11626145, 0.78195621],
       [0.

In [20]:
# probabilities sum up to 1
gbrt.predict_proba(X_test).sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

In [22]:
np.argmax(gbrt.predict_proba(X_test), axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [23]:
gbrt.predict(X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [27]:
np.all(gbrt.predict(X_test) == np.argmax(gbrt.predict_proba(X_test), axis=1))

np.True_

In [38]:
# make sure to use the classes_ attribute since order not guaranteed for classes

from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

named_target = iris.target_names[y_train]
logreg.fit(X_train, named_target)

print(logreg.classes_)
print(logreg.predict(X_test)[:10])

argmax_dec_func = np.argmax(logreg.decision_function(X_test), axis=1)
print(argmax_dec_func[:10])
logreg.classes_[argmax_dec_func][:10]

['setosa' 'versicolor' 'virginica']
['versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'versicolor']
[1 0 2 1 1 0 1 2 1 1]


array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor'],
      dtype='<U10')